[package]
name = "reset_bst_linux_adapter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bst_reset_rust = { path = "../bst-reset-rust/"}